### ISSUE TITLE
Google auth error

### ISSUE THREAD

**Issue by ghost** [mgp25/Snap-API#66]
This morning I'm getting this error at google auth step when loggin in:

`Error=NeedsBrowser Url=https://www.google.com/accounts/ContinueSignIn?sarp=1&scc=1&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Fandroid%2Fauth%3Fhl%3Den_US_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbvECfHQkXJl6WvcAFxYUwOXx6Xw6l55ZaFZ7deTvp_68ITZAnn_bwJc6BVkps_HNZnfcfY31tOev0ET-DzhA4E2iZsnTtMmIsq8c3P5dXBcyGx7wSzu2jVwNoBMFXAnzKKGSdXJ0IAyFWPUenyDcfUGt1DNzrris0nJR12zJ_B0_zCmHx2RaWjfIBN6HEC6wV0wGiSLjeR6gyHvuHLZxx38A554jaijwWNBF69kGGlPMoR3UC0 ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.`

**Comment by Snowlav** [comment]
You have 2 step authentication enabled on that account, use a dummy mail.

**Comment by ghost** [comment]
@Snowlav The google account was grabbed from mgp25's server. I'd love to know how to use my owne account, i.e., how to generate encrypted password of my ownn account.

**Comment by mgp25** [comment]
@rpw98 you can remove `EncryptedPasswd` and use simply `Password` to use your own account's password, btw use auth, not to logging everytime, remain logged in.

**Comment by ghost** [comment]
@mgp25 I see. Thanks. I'll give it a try. Yes, I remain logged in as much as I can :-)

**Comment by ghost** [comment]
It worked. Thanks!

**Comment by boyyy** [comment]
@Snowlav What do you mean with dummy mail?
Use a dummy mail instead of the email generate by mgp25's server?

**Comment by pravinshinde** [comment]
I found the same error message.

Exception in thread "main" com.akdeniz.googleplaycrawler.GooglePlayException: Error=NeedsBrowser
Url=https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&continue=https%3A%2F%2Faccounts.google.com%2Fo%2Fandroid%2Fauth%3Fhl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbtD2AanDIXuqAJo78FowkqJ_6cKDLEzuHbc9tpViqOXn0uX7BF5TfFCMNyECu11P672LYdUJvifjOd4XrqIspdv0LN-JFF8n-FMP-G7mzs2s2idy6ad0qCMmSBJBDLoDXGs4Khs3m3Dnf4_MGWWO-WWsvySSnGnPBQdiWJxkW8bQ2z2dvFvNTYBiuav7W94oHWihM5qWN-ABJX2ajE_qUe7N2woDmZvZW9fvGv87QQjNOkhQ24
ErrorDetail=To access your account, you must sign in on the web. Touch Next to start browser sign-in.


	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:522)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:482)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:462)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.loginAC2DM(GooglePlayAPI.java:180)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.checkin(GooglePlayAPI.java:160)
	at com.info.playservice.GooglePlayService.createService(GooglePlayService.scala:49)
	at com.info.playservice.GooglePlayService.loginToPlayService(GooglePlayService.scala:79)
	at com.info.playservice.GooglePlayService.<init>(GooglePlayService.scala:36)
	at com.info.boot.free.BootFreeApps$.delayedEndpoint$com$info$boot$free$BootFreeApps$1(BootFreeAppsSelenium.scala:24)
	at com.info.boot.free.BootFreeApps$delayedInit$body.apply(BootFreeAppsSelenium.scala:20)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at com.info.boot.free.BootFreeApps$.main(BootFreeAppsSelenium.scala:20)
	at com.info.boot.free.BootFreeApps.main(BootFreeAppsSelenium.scala)
